In [21]:
#Importar librer√≠as
import pandas as pd
import numpy as np
import pickle


save_path = r'C:\Users\ctrujils\eficiencia_promocional\maestro_cliente_final_segmentado.parquet'
maestro_clientes=pd.read_parquet(save_path)

##### Checkeo de tipologia / pdv

In [24]:
# maestro_clientes[maestro_clientes['company_name']=='YORI']

In [25]:
path = r'C:\Users\ctrujils\order_detail_sorted_normalizado.parquet'
order_detail = pd.read_parquet(path)

In [26]:
agrupado=order_detail.groupby(['Code','PointOfSaleId','NameDistributor']).count().reset_index()

agrupado

,Code,PointOfSaleId,NameDistributor,OrderDate,Sellout,CodeProduct,Name,CouponCode,CouponDiscountAmt,CouponDiscountPct,...,NormalizedCoupon,Frequency_online,Coupon_type,PctgCouponUsed,DaysBetweenPurchases,CumulativeAvgDaysBetweenPurchases,IsOnline,LastPurchaseOnline,Digitalizacion,ForwardOnline
0,,100406,Voldis Murcia,2,2,2,2,0,2,2,...,2,2,2,2,2,2,2,2,2,2
1,,100421,Voldis Murcia,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,,100564,Voldis Murcia,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,,100618,Voldis Murcia,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,,100630,Voldis Murcia,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689757,VBF24-005-754,CLI0029271,Voldis Madrid,1,1,1,1,0,1,1,...,1,0,1,1,0,0,1,1,1,1
689758,VBF24-005-755,CLI0029272,Voldis Madrid,1,1,1,1,0,1,1,...,1,0,1,1,0,0,1,1,1,1
689759,VBF24-005652,CLI0024414,Voldis Granada,1,1,1,1,0,1,1,...,1,0,1,1,0,0,1,1,1,1
689760,VBF24-005705,CLI0024942,Voldis Granada,1,1,1,1,0,1,1,...,1,0,1,1,0,0,1,1,1,1
689761,VBF24-005725,CLI0025141,Voldis Granada,1,1,1,1,0,1,1,...,1,0,1,1,0,0,1,1,1,1

In [28]:
# Configuraci√≥n para mostrar los n√∫meros en formato est√°ndar (sin notaci√≥n cient√≠fica)
pd.options.display.float_format = '{:,.2f}'.format

order_detail_sorted=order_detail[(order_detail['OrderDate']> '2023-01-01')&(order_detail['OrderDate']< '2023-12-30')]

suma_coupons_por_distribuidor = order_detail_sorted['CouponDiscountAmt'].sum()

suma_coupons_por_distribuidor

705290.1500120331

In [29]:
order_detail_sorted['PointOfSaleId'].nunique()

17632

In [33]:
order_detail_sorted

,PointOfSaleId,IsOnline,LastPurchaseOnline,Digitalizacion,ForwardOnline
0,00134,False,False,0.00,False
1,00134,False,False,0.00,False
2,00134,False,False,0.00,False
3,00134,False,False,0.00,False
4,00134,False,False,0.00,False
...,...,...,...,...,...
688656,CLI0050979,False,False,0.00,False
688657,CLI0050979,False,False,0.00,False
688658,CLI0050979,False,False,0.00,False
689218,CLI0051062,False,False,0.00,False
689231,CLI0051064,False,False,0.00,False

In [36]:
# Filtrar maestro_clientes para que solo queden los PDVs que est√°n en order_detail_sorted
maestro_clientes_filtrado = maestro_clientes[maestro_clientes['company_id'].isin(order_detail_sorted['PointOfSaleId'].unique())]

# Mostrar algunos resultados para verificar
maestro_clientes_filtrado

,company_id,store_id,store_id_long,company_name,codigo_postal,store_name,tipologia,provincia,poblacion,autonomia,...,abc_mean,PointOfSaleId,IsOnline,LastPurchaseOnline,Digitalizacion,ForwardOnline,NumberOfOrders,SegmentoFrecuencia,SegmentoFacturacionOnline,SegmentoReferenciasUnicas
0,01718,1,7E27D492-A885-4DC3-939E-AB718B667C8B,EL PUERTO,28018,BEBICER,No Segmentado,Madrid,Madrid,Madrid,...,B,01718,False,False,0.00,False,29.00,None,None,B
1,01718,1,7E27D492-A885-4DC3-939E-AB718B667C8B,EL PUERTO,28018,BEBICER,No Segmentado,Madrid,Madrid,Madrid,...,B,01718,False,False,0.00,False,29.00,None,None,B
2,01718,1,7E27D492-A885-4DC3-939E-AB718B667C8B,EL PUERTO,28018,BEBICER,No Segmentado,Madrid,Madrid,Madrid,...,B,01718,False,False,0.00,False,29.00,None,None,B
3,01718,1,7E27D492-A885-4DC3-939E-AB718B667C8B,EL PUERTO,28018,BEBICER,No Segmentado,Madrid,Madrid,Madrid,...,B,01718,False,False,0.00,False,29.00,None,None,B
4,01718,1,7E27D492-A885-4DC3-939E-AB718B667C8B,EL PUERTO,28018,BEBICER,No Segmentado,Madrid,Madrid,Madrid,...,B,01718,False,False,0.00,False,29.00,None,None,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2316109,CLI0034744,7,9CC0BCF9-4378-40A7-B258-A01FBDD9A7E2,ALIMENTACION CHINA,28020,Voldis Madrid BC,No Segmentado,Madrid,Madrid,Madrid,...,None,CLI0034744,False,False,0.00,False,1.00,None,None,C
2316115,CLI0042028,11,652c6174-39ac-4ca8-b4da-56dac5baf93b,BAR SAMY (SOL),46019,Voldis Valencia BC,No Segmentado,Valencia,Valencia,Comunidad Valenciana,...,None,CLI0042028,True,False,1.00,True,2.00,C,C,C
2316116,CLI0042028,11,652c6174-39ac-4ca8-b4da-56dac5baf93b,BAR SAMY (SOL),46019,Voldis Valencia BC,No Segmentado,Valencia,Valencia,Comunidad Valenciana,...,None,CLI0042028,True,False,1.00,True,2.00,C,C,C
2316117,CLI0042028,11,652c6174-39ac-4ca8-b4da-56dac5baf93b,BAR SAMY (SOL),46019,Voldis Valencia BC,No Segmentado,Valencia,Valencia,Comunidad Valenciana,...,None,CLI0042028,True,True,2.00,True,2.00,C,C,C
2316118,CLI0042028,11,652c6174-39ac-4ca8-b4da-56dac5baf93b,BAR SAMY (SOL),46019,Voldis Valencia BC,No Segmentado,Valencia,Valencia,Comunidad Valenciana,...,None,CLI0042028,True,True,2.00,True,2.00,C,C,C

In [39]:
maestro_clientes_filtrado=maestro_clientes_filtrado.drop_duplicates(subset=['tipologia','company_id','store_id'])

In [41]:
maestro_clientes_filtrado.groupby('tipologia')['company_id'].count()

tipologia
Bar Tradicional                     952
Cervecer√≠a                          145
Discoteca                            51
Establecimiento de Tapeo           1197
No Segmentado                      9049
Noche Temprana                      232
Pasteler√≠a/Cafeter√≠a/Panader√≠a      367
Restaurante                         619
Restaurante de Imagen               370
Restaurante de Imagen con Tapeo     217
Tap room                              8
Name: company_id, dtype: int64

In [42]:
maestro_cliente_path= r'C:\Users\ctrujils\maestro_cliente_final_segmentado.parquet'
maestro_clientes_filtrado.to_parquet(maestro_cliente_path)